### PR TITLE
Use Prettier

### PR DESCRIPTION
**Pull request by mrtnzlml**

### CODE REVIEW

**Comment by jaroslav-kubicek** [comment]
why not https://standardjs.com/ ? 😢

**Comment by mrtnzlml** [comment]
Because we are using Prettier in the Prague office. But you are reviewer so if you don't like it - I am OK with that. I just think that Prettier is more pretty... :)

**Comment by jaroslav-kubicek** [comment]
I'm okay with that, we shouldn't just combine these two together, therefore I suggest to remove standard entirely.

**Comment by mrtnzlml** [comment]
As you wish...

**Pull request merged**
